### ISSUE TITLE
ValueError: expected sequence of length 8 at dim 1 (got 3)

### ISSUE THREAD

**Issue by yeshihai** [wyn430/CPAC-CNN#1]
There are some problems appeared when I run the code "python train_mnist.py 8 3 6 10 cuda:0",:
`# python train_mnist.py 8 3 6 10 cuda:0Traceback (most recent call last):  File "train_mnist.py", line 128, in <module>    Net = CNN_Decomp(num_filters, filter_h, filter_w, image_channels, rank, devices, num_class, input_shape)  File "/home/yeshihai/code/glp/CPAC-CNN/CPAC-CNN-GPU/cnn_torch.py", line 20, in __init__    self.conv1 = Conv_Decomp(num_filters, filter_h, filter_w, image_channels, rank, devices)  File "/home/yeshihai/code/glp/CPAC-CNN/CPAC-CNN-GPU/conv_decomp_torch.py", line 31, in __init__    self.factor1 = nn.Parameter(torch.tensor(factors[1]).to(devices[0]))ValueError: expected sequence of length 8 at dim 1 (got 3)`

I'm not sure if the problem is caused by the environment or the code itself

**Comment by wyn430** [comment]
> There are some problems appeared when I run the code "python train_mnist.py 8 3 6 10 cuda:0",: `# python train_mnist.py 8 3 6 10 cuda:0Traceback (most recent call last): File "train_mnist.py", line 128, in <module> Net = CNN_Decomp(num_filters, filter_h, filter_w, image_channels, rank, devices, num_class, input_shape) File "/home/yeshihai/code/glp/CPAC-CNN/CPAC-CNN-GPU/cnn_torch.py", line 20, in __init__ self.conv1 = Conv_Decomp(num_filters, filter_h, filter_w, image_channels, rank, devices) File "/home/yeshihai/code/glp/CPAC-CNN/CPAC-CNN-GPU/conv_decomp_torch.py", line 31, in __init__ self.factor1 = nn.Parameter(torch.tensor(factors[1]).to(devices[0]))ValueError: expected sequence of length 8 at dim 1 (got 3)`
> 
> I'm not sure if the problem is caused by the environment or the code itself

The code is tested on the environment listed in the repo. Could you please double-check the version of "tensorly" and its output? It looks to me because the CP-decomposition results are not as expected.
